version: 2

# Build tools and environment setup
build:
  os: ubuntu-24.04
  tools:
    python: miniconda-latest # miniforge3-latest before miniforge because available
  apt_packages:
    - git 
    - xvfb 
    - imagemagick 
    - poppler-utils 
    - latexmk 
    - texlive-latex-recommended 
    - texlive-latex-extra 
    - texlive-fonts-recommended
  # Build commands for HTML and PDF
  commands:
    - conda env update --file pipe1669.yml -y
    - python -m pip install .[docs] && mkdir -p ~/.casa/data
    - mkdir -p ~/.casa/data
    - cd docs && make html_docs
    - cd docs && make latexpdf      

conda:
  environment: pipe1669.yml
 
# Sphinx configuration
sphinx:
  configuration: docs/conf.py        



