version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "latest"
  apt_packages:
    - xvfb
    - imagemagick
    - poppler-utils
    - latexmk
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-recommended
  jobs:
    create_environment:
      - asdf plugin add pixi
      - asdf install pixi latest
      - asdf global pixi latest
      - mkdir -p ~/.casa/data
    install:
      - pixi install -e docs
    build:
      html:
        - pixi run -e docs --frozen sphinx-build -T -b html docs/source $READTHEDOCS_OUTPUT/html
      pdf:
        - pixi run -e docs --frozen sphinx-build -T -b latex docs/source docs/_build/latex
        - cd docs/_build/latex && latexmk -pdf -interaction=nonstopmode *.tex
        - mkdir -p $READTHEDOCS_OUTPUT/pdf/
        - cp docs/_build/latex/*.pdf $READTHEDOCS_OUTPUT/pdf/
