version: 2

# Build tools and environment setup
build:
  os: ubuntu-24.04
  tools:
    python: "3.10"

build:
  os: "ubuntu-24.04"
  tools:
    python: "mambaforge-22.9"
  apt_packages:
    - git 
    - xvfb 
    - imagemagick 
    - poppler-utils 
    - latexmk 
    - texlive-latex-recommended 
    - texlive-latex-extra 
    - texlive-fonts-recommended

conda:
  environment: pipe1669.yml
 

python:
  install:
    - method: pip
      path: .[docs]
        

# Sphinx configuration
sphinx:
  configuration: docs/conf.py        


# Build commands for HTML and PDF
commands:
  - mkdir -p ~/.casa/data
  - cd docs && make html_docs
  - cd docs && make latexpdf  

# Build output formats
formats:
  - html
  - pdf  