"""
QA handlers for hifa_bandpass task.
"""

import os

import pipeline.infrastructure.logging as logging
import pipeline.infrastructure.pipelineqa as pqa
import pipeline.infrastructure.renderer.rendererutils as rutils
import pipeline.infrastructure.utils as utils
import pipeline.qa.scorecalculator as qacalc
from pipeline.hif.tasks.bandpass.common import BandpassResults
from pipeline.hif.tasks.bandpass.qa import BandpassQAHandler
from .almaphcorbandpass import ALMAPhcorBandpass

LOG = logging.get_logger(__name__)


class AlmaBandpassQAHandler(pqa.QAPlugin):
    """
    QA handler for a BandpassResults generated by hifa_bandpass.
    """

    result_cls = BandpassResults
    child_cls = None
    generating_task = ALMAPhcorBandpass

    def handle(self, context, result):
        # Invoke QA handler for base BandpassResults (shared with hif_bandpass).
        base_handler = BandpassQAHandler()
        base_handler.handle(context, result)

        # Run local QA handlers.
        for handler in [
            _phaseup_combine_handler,
            _phaseup_missing_handler,
            _phaseup_snr_handler,
        ]:
            result.qa.pool.extend(handler(result))


def _phaseup_combine_handler(result: BandpassResults) -> list[pqa.QAScore]:
    """
    Generate QA score for whether bandpass phase-up used spw combination.

    Args
        result: the task Result to inspect.

    Returns:
        A list of QA scores informing about spw combination in phase-up.
    """
    # No QA score if phase-up results are absent.
    if not result.preceding:
        return []

    # Step through every CalApp to find and score the phase-up caltable.
    scores = []
    for calapp_list in result.preceding:
        for calapp in calapp_list:
            # Skip the phase-offset tables (created with solint='inf').
            if utils.get_origin_input_arg(calapp, 'solint') == 'inf':
                continue

            # Evaluate whether CalApp used spw combination.
            combine = utils.get_origin_input_arg(calapp, 'combine')
            # If SpW combination was used, turn this into a blue QA score.
            if combine == 'spw':
                score = rutils.SCORE_THRESHOLD_SUBOPTIMAL
                longmsg = f"{calapp.vis}: Spectral window combination used to improve phase-up solution SNR."
                shortmsg = f"Spw combination used in phase-up"
            else:
                score = 1.0
                longmsg = f"{calapp.vis}: No spectral window combination necessary for phase-up solution."
                shortmsg = f"No spw combination used in phase-up"
            qascore = pqa.QAScore(
                score,
                longmsg=longmsg,
                shortmsg=shortmsg,
                weblog_location=pqa.WebLogLocation.ACCORDION,
                origin=pqa.QAOrigin(
                    metric_name='bandpass.phaseup.combine',
                    metric_score=score,
                    metric_units='Score based on whether bandpass phaseup used combine',
                ),
                hierarchy="bandpass.phaseup.combine",
                applies_to=pqa.TargetDataSelection(vis={calapp.vis}),
            )
            scores.append(qascore)

    return scores


def _phaseup_missing_handler(result: BandpassResults) -> list[pqa.QAScore]:
    """
    Generate QA score for whether bandpass phase-up is missing.

    Args
        result: the task Result to inspect.

    Returns:
        A list of QA scores on presence of bandpass phase-up solutions.
    """
    # No QA score if result.preceding is populated (assumed to be with bandpass
    # phase-up result).
    if result.preceding:
        return []

    # Adjust QA message based on whether it is intentional that the phase-up
    # solution is missing.
    hm_phaseup = result.inputs["hm_phaseup"]
    vis = os.path.basename(result.inputs["vis"])
    if hm_phaseup == '':
        score = 1.0
        longmsg = f"{vis}: skipped bandpass phase-up solution (disabled with hm_phaseup='')."
        shortmsg = f"No phase-up computed"
    else:
        score = 0.0
        longmsg = (f"{vis}: bandpass phase-up solution missing from results, even though it should have been computed"
                   f" (hm_phaseup = {hm_phaseup}).")
        shortmsg = f"No phase-up found"

    qascore = pqa.QAScore(
        score,
        longmsg=longmsg,
        shortmsg=shortmsg,
        weblog_location=pqa.WebLogLocation.ACCORDION,
        origin=pqa.QAOrigin(
            metric_name="bandpass.phaseup.missing",
            metric_score=score,
            metric_units="Presence of bandpass phase-up.",
        ),
        hierarchy="bandpass.phaseup.missing",
        applies_to=pqa.TargetDataSelection(vis={vis}),
    )

    return [qascore]


def _phaseup_snr_handler(result: BandpassResults) -> list[pqa.QAScore]:
    """
    Generate QA score for the expected phase-up SNR for the bandpass calibrator.

    Args
        result: the task Result to inspect.

    Returns:
        A list of QA scores informing about expected phase-up SNR.
    """
    # No QA score if expected phase-up SNR is absent.
    if not result.phaseup_snr_expected:
        return []

    vis = result.inputs["vis"]
    snr_expected = result.phaseup_snr_expected
    snr_threshold = result.inputs['phaseupsnr']

    if snr_expected <= 0.3 * snr_threshold:
        score = rutils.SCORE_THRESHOLD_ERROR
        shortmsg = 'Low bandpass phase-up SNR'
        longmsg = (f'{vis}: expected bandpass phase-up SNR ({snr_expected:.1f}) is <= 30% of the phase SNR'
                   f' threshold ({snr_threshold:.1f}).')
    elif snr_expected <= 0.5 * snr_threshold:
        score = rutils.SCORE_THRESHOLD_WARNING
        shortmsg = 'Low bandpass phase-up SNR'
        longmsg = (f'{vis}: expected bandpass phase-up SNR ({snr_expected:.1f}) is <= 50% of the phase SNR'
                   f' threshold ({snr_threshold:.1f}).')
    elif snr_expected <= 0.75 * snr_threshold:
        score = rutils.SCORE_THRESHOLD_SUBOPTIMAL
        shortmsg = 'Low bandpass phase-up SNR'
        longmsg = (f'{vis}: expected bandpass phase-up SNR ({snr_expected:.1f}) is <= 75% of the phase SNR'
                   f' threshold ({snr_threshold:.1f}).')
    else:
        score = 1.0
        shortmsg = 'Bandpass phase-up SNR is ok'
        longmsg = (f'{vis}: expected bandpass phase-up SNR ({snr_expected:.1f}) is > 75% of the phase SNR'
                   f' threshold ({snr_threshold:.1f}).')

    qascore = pqa.QAScore(
        score,
        longmsg=longmsg,
        shortmsg=shortmsg,
        weblog_location=pqa.WebLogLocation.ACCORDION,
        origin=pqa.QAOrigin(
            metric_name='bandpass.phaseup.snr',
            metric_score=snr_expected,
            metric_units='Phase-up SNR',
        ),
        hierarchy="bandpass.phaseup.snr",
        applies_to=pqa.TargetDataSelection(vis={vis}),
    )

    return [qascore]
