import sys

import pipeline.h.cli.utils as utils


# docstring and type hints: inherits from hif.tasks.lowgainflag.lowgainflag.LowgainflagInputs.__init__
@utils.cli_wrapper
def hif_lowgainflag(vis=None, intent=None, spw=None, refant=None, flag_nmedian=None, fnm_lo_limit=None,
                    fnm_hi_limit=None, tmef1_limit=None):
    """Flag antennas with low or high gain

    Deviant antennas are detected by outlier analysis of a view showing their
    amplitude gains, pre-applying a temporary bandpass and phase solution.
    This view is a list of 2D images with axes 'Scan' and 'Antenna'; there
    is one image for each spectral window and intent. A flagcmd to flag all data
    for an antenna will be generated by any gain that is outside the range
    [fnm_lo_limit * median, fnm_hi_limit * median].

    Returns:
        The results object for the pipeline task is returned.

    Examples:
        1. Flag antennas with low or high gain using recommended thresholds:

        >>> hif_lowgainflag()

    """
    ##########################################################################
    #                                                                        #
    #  CASA task interface boilerplate code starts here. No edits should be  #
    #  needed beyond this point.                                             #
    #                                                                        #
    ##########################################################################

    # create a dictionary containing all the arguments given in the
    # constructor
    all_inputs = vars()

    # get the name of this function for the weblog, eg. 'hif_flagdata'
    task_name = sys._getframe().f_code.co_name

    # get the context on which this task operates
    context = utils.get_context()

    # execute the task
    results = utils.execute_task(context, task_name, all_inputs)

    return results
