############################################################################
#
# setup:
#
#   install mambaforge: the recommended minimal conda installer
#     https://github.com/conda-forge/miniforge#mambaforge
#
#   step-by-step to reproduce the Pipeline/CASA environment
#     $ mamba env create -f pipeline.yaml
#     $ mamba activate pipeline
#     $ pip install -r pipeline_casa6.txt
#
#   update:
#     $ conda update -n pipeline --all
#     $ mamba env update -f pipeline.yaml
#
# execute:
#     $ xvfb-run -a python run_pipeline.py
#
# Changlog:
#     20221105: last tested against the modular casa ver=6.5.2
#
############################################################################

name: pipe1682

channels:
  - conda-forge
  - defaults

dependencies:
  
  # core
  - python=3.8    # the casa packages wheels are not available for Python 3.9 yet, therefore
                  # Python 3.8 is used.
  - ipython
  - pip
  - conda-ecosystem-user-package-isolation  # https://github.com/conda-forge/conda-ecosystem-user-package-isolation-feedstock
                                            # prevent Python and R from searching for packages outside of the current environment
  - numpy
  - matplotlib
  - scipy
  - certifi
  - protobuf=3.20 # casatplotms requires ver<=3.20 at this moment
  - mpi4py
  
  # extra/optional
  - astropy
  - pympler
  - jupyterlab
  - future
  - johnnydep
  - line_profiler
  - memory_profiler
  - pylint
  - flake8
  - isort
  - black
  - pytest
  - pydocstyle
  - pycodestyle
  - pytest-cov
  - pytest-pep8


  - pip:
    # the casa package versions are not specified here therefore the latest versions from PyPI are used.
    - casatools
    - casatasks
    - casadata
    - casaplotms
    - casaviewer
    - casampi
    - almatasks
    - casashell
